# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 18:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('multiplier', models.PositiveSmallIntegerField(default=1)),
                ('goal', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('value', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DropUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('challenges', models.ManyToManyField(to='dropchain.Challenge')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('value', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('value', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('1', '1'), ('3', '2'), ('3', '3')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('goal', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='priority',
            name='project',
            field=models.ManyToManyField(to='dropchain.Project'),
        ),
        migrations.AddField(
            model_name='dropuser',
            name='priorities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropchain.Priority'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='days',
            field=models.ManyToManyField(to='dropchain.Day'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='hours',
            field=models.ManyToManyField(to='dropchain.Hour'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='months',
            field=models.ManyToManyField(to='dropchain.Month'),
        ),
    ]
