# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
    ]
