# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropchain', '0002_typechallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='typechallenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropchain.TypeChallenge'),
        ),
    ]
