# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropchain', '0004_auto_20170512_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='days',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='months',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='typechallenge',
            name='days',
            field=models.ManyToManyField(to='dropchain.Day'),
        ),
        migrations.AddField(
            model_name='typechallenge',
            name='hours',
            field=models.ManyToManyField(to='dropchain.Hour'),
        ),
        migrations.AddField(
            model_name='typechallenge',
            name='months',
            field=models.ManyToManyField(to='dropchain.Month'),
        ),
        migrations.AddField(
            model_name='typechallenge',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
