# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropchain', '0006_typechallenge_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropuser',
            name='priorities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dropchain.Priority'),
        ),
    ]
